services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - CHAT_HOST=0.0.0.0
      - CHAT_PORT=8000
      - CHAT_LOG_LEVEL=INFO
      - CHAT_LLM_PROVIDER=openrouter
      - CHAT_OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - CHAT_DATABASE_URL=sqlite+aiosqlite:///./data/chat.db
      - CHAT_RATE_LIMIT=60/minute
    volumes:
      - ./data:/app/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s