version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - API_PORT=8000
      - API_HOST=0.0.0.0
      - LOG_LEVEL=INFO
      - LOG_FORMAT=json
      - REQUIRE_API_KEY=false
      - LLM_PROVIDER=mock
      - ENABLE_CACHE=true
      - DATABASE_PATH=chat_history.db
    volumes:
      - ./data:/app/data:rw
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s