name: CI

on:
  pull_request: { branches: [main] }

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11', cache: pip }
      - run: pip install -e ".[dev,test]"
      - run: ruff check src/
      - run: mypy src/
      - run: pytest tests/ --cov=src
      - uses: codecov/codecov-action@v4

  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          docker build -t test .
          docker run -d --name api -p 8000:8000 test
          sleep 10 && curl -f http://localhost:8000/v1/health
