name: Cleanup AWS Resources

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: 'Type "destroy" to confirm resource deletion'
        required: true
        type: string

env:
  AWS_REGION: 'us-east-1'
  TERRAFORM_VERSION: '1.5.0'

jobs:
  cleanup:
    if: github.event.inputs.confirm == 'destroy'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}
      
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      
      - name: Terraform Destroy
        working-directory: iac/terraform
        continue-on-error: true
        run: |
          terraform init -reconfigure
          terraform destroy -auto-approve \
            -var="gemini_api_key=dummy" \
            -var="openrouter_api_key=dummy" \
            -var="api_key=dummy" || true
      
      - name: Manual Cleanup (fallback)
        continue-on-error: true
        run: |
          # Delete Lambda
          aws lambda delete-function --function-name serverless-chat-api-dev || true
          
          # Delete ECR
          aws ecr delete-repository --repository-name serverless-chat-api-dev --force || true
          
          # Delete CloudWatch Logs
          aws logs delete-log-group --log-group-name /aws/lambda/serverless-chat-api-dev || true
          
          # Delete DynamoDB
          aws dynamodb delete-table --table-name serverless-chat-api-dev || true
          
          # Delete IAM
          aws iam delete-role-policy --role-name serverless-chat-api-lambda-dev --policy-name serverless-chat-api-lambda-policy || true
          aws iam detach-role-policy --role-name serverless-chat-api-lambda-dev --policy-arn arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole || true
          aws iam delete-role --role-name serverless-chat-api-lambda-dev || true
          
          # Clear S3 state
          aws s3 rm s3://serverless-chat-api-terraform-state/ --recursive || true
      
      - name: Summary
        run: echo "✅ Cleanup complete!"